services:
  - type: web
    name: taskit-backend
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"

    envVars:
      - key: FRONT_END_URL
        value: "https://taskit-man.vercel.app"

      - key: MONGO_URI
        sync: false  

      - key: JWT_SECRET
        sync: false

      - key: ADMIN_JOIN_CODE
        sync: false
